### ISSUE TITLE
Decide on naming.

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainglobe-napari#40]
`brainrender` is pretty popular, has a published paper, and Fede has spent a long time working on it. For this reason I think the napari port of BrainGlobe's 3D visualisation should keep the brainrender name. I can see two options:
- Rename this plugin to `brainrender-napari` and any other (non-visualisation) functionality lives elsewhere
- Keep the `brainrender-napari` name as a general plugin, but make sure there's a widget or something that is specifically named brainrender.

Any thoughts @alessandrofelder

**Comment by alessandrofelder** [comment]
I think this is a good idea, and I would favour the first option, ie renaming to `brainrender-napari`?

**Comment by adamltyson** [comment]
Fine by me. `brainglobe-napari` could end up becoming a napari-specific metapackage? i.e. only include what can be run through napari?

**Comment by alessandrofelder** [comment]
Naming decided, so closing. Renaming to happen as part of #44 .
